# Generated by Django 4.1.1 on 2022-09-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_share_app', '0002_alter_picturefolder_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturefolder',
            name='piture_folder_password',
            field=models.CharField(max_length=100),
        ),
    ]
