# Generated by Django 4.1.1 on 2022-09-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_share_app', '0003_alter_picturefolder_piture_folder_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturefolder',
            name='piture_folder_password',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
